* Course
** Source
"Category Theory for Programmers" by Bartosz Milewski.
Found at: https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/
** Category Theory for Programmers: The Preface
*** Composition is the essence of programming
"I will attempt, in the space of a few paragraphs, to convince you that this book is written for you, and whatever objections you might have to learning one of the most abstract branches of mathematics in your “copious spare time” are totally unfounded.

My optimism is based on several observations. First, category theory is a treasure trove of extremely useful programming ideas. Haskell programmers have been tapping this resource for a long time, and the ideas are slowly percolating into other languages, but this process is too slow. We need to speed it up.

Second, there are many different kinds of math, and they appeal to different audiences. You might be allergic to calculus or algebra, but it doesn’t mean you won’t enjoy category theory. I would go as far as to argue that category theory is the kind of math that is particularly well suited for the minds of programmers. That’s because category theory — rather than dealing with particulars — deals with structure. It deals with the kind of structure that makes programs composable.

Composition is at the very root of category theory — it’s part of the definition of the category itself. And I will argue strongly that composition is the essence of programming."
*** Side effects don't scale
"One of the forces that are driving the big change is the multicore revolution. The prevailing programming paradigm, object oriented programming, doesn’t buy you anything in the realm of concurrency and parallelism, and instead encourages dangerous and buggy design. Data hiding, the basic premise of object orientation, when combined with sharing and mutation, becomes a recipe for data races. The idea of combining a mutex with the data it protects is nice but, unfortunately, locks don’t compose, and lock hiding makes deadlocks more likely and harder to debug.

But even in the absence of concurrency, the growing complexity of software systems is testing the limits of scalability of the imperative paradigm. To put it simply, side effects are getting out of hand. Granted, functions that have side effects are often convenient and easy to write. Their effects can in principle be encoded in their names and in the comments. A function called SetPassword or WriteFile is obviously mutating some state and generating side effects, and we are used to dealing with that. It’s only when we start composing functions that have side effects on top of other functions that have side effects, and so on, that things start getting hairy. It’s not that side effects are inherently bad — it’s the fact that they are hidden from view that makes them impossible to manage at larger scales. Side effects don’t scale, and imperative programming is all about side effects."
** 1.1 Category: The Essence of Composition
*** What is a category?
A category is an embarrassingly simple concept. A category consists of objects and arrows that go between them. That’s why categories are so easy to represent pictorially. An object can be drawn as a circle or a point, and an arrow… is an arrow.
*** Arrows compose
The essence of a category is composition. Or, if you prefer, the essence of composition is a category. Arrows compose, so if you have an arrow from object A to object B, and another arrow from object B to object C, then there must be an arrow — their composition — that goes from A to C.
**** Arrows are also called "morphisms"
*** 2 requirements for categories
A category consists of objects and arrows (morphisms). Arrows can be composed, and the composition is associative. Every object has an identity arrow that serves as a unit under composition.
**** Arrows / morphisms must be associative
Associative reminder: (a + b) + c == a + (b + c)
Addition is associative.
**** Every object must have an identity arrow
*** We need abstraction
How do we solve problems? We decompose bigger problems into smaller problems. If the smaller problems are still too big, we decompose them further, and so on. Finally, we write code that solves all the small problems. And then comes the essence of programming: we compose those pieces of code to create solutions to larger problems. Decomposition wouldn’t make sense if we weren’t able to put the pieces back together.

This process of hierarchical decomposition and recomposition is not imposed on us by computers. It reflects the limitations of the human mind. Our brains can only deal with a small number of concepts at a time. The bottom line is that we are unable to deal with the soup of objects or the spaghetti of code. We need structure not because well-structured programs are pleasant to look at, but because otherwise our brains can’t process them efficiently. We often describe some piece of code as elegant or beautiful, but what we really mean is that it’s easy to process by our limited human minds. Elegant code creates chunks that are just the right size and come in just the right number for our mental digestive system to assimilate them.
** 1.2 Who Needs Types?
*** Static vs dynamic types
Do we want to make people happy, or do we want to produce correct programs?
*** Types are about composability
Category theory is about composing arrows. But not any two arrows can be composed. The target object of one arrow must be the same as the source source object of the next arrow. In programming we pass the results on one function to another. The program will not work if the target function is not able to correctly interpret the data produced by the source function. The two ends must fit for the composition to work. The stronger the type system of the language, the better this match can be described and mechanically verified.
*** Category: Set
In Set, objects are sets and morphisms (arrows) are functions.

Set is a very special category, because we can actually peek inside its objects and get a lot of intuitions from doing that. For instance, we know that an empty set has no elements. We know that there are special one-element sets. We know that functions map elements of one set to elements of another set. They can map two elements to one, but not one element to two. We know that an identity function maps each element of a set to itself, and so on. The plan is to gradually forget all this information and instead express all those notions in purely categorical terms, that is in terms of objects and arrows.
*** Operational vs denotational semantics
operational semantics describes the mechanics of program execution. It defines a formalized idealized interpreter. The semantics of industrial languages, such as C++, is usually described using informal operational reasoning, often in terms of an “abstract machine.”

The problem is that it’s very hard to prove things about programs using operational semantics. To show a property of a program you essentially have to “run it” through the idealized interpreter.

It doesn’t matter that programmers never perform formal proofs of correctness. We always “think” that we write correct programs. Nobody sits at the keyboard saying, “Oh, I’ll just throw a few lines of code and see what happens.” We think that the code we write will perform certain actions that will produce desired results. We are usually quite surprised when it doesn’t. That means we do reason about programs we write, and we usually do it by running an interpreter in our heads. It’s just really hard to keep track of all the variables. Computers are good at running programs — humans are not! If we were, we wouldn’t need computers.

But there is an alternative. It’s called denotational semantics and it’s based on math. In denotational semantics every programing construct is given its mathematical interpretation. With that, if you want to prove a property of a program, you just prove a mathematical theorem. You might think that theorem proving is hard, but the fact is that we humans have been building up mathematical methods for thousands of years, so there is a wealth of accumulated knowledge to tap into. Also, as compared to the kind of theorems that professional mathematicians prove, the problems that we encounter in programming are usually quite simple, if not trivial.
*** Pure functions
The things we call functions in C++ or any other imperative language, are not the same things mathematicians call functions. A mathematical function is just a mapping of values to values.

In programming languages, functions that always produce the same result given the same input and have no side effects are called pure functions. In a pure functional language like Haskell all functions are pure.
*** Types are sets
Types are sets in the category Set, and the morphisms are pure functions.
**** Absurd
What’s the type corresponding to an empty set? This type is called "Void" in Haskell. It’s a type that’s not inhabited by any values. You can define a function that takes Void, but you can never call it. To call it, you would have to provide a value of the type Void, and there just aren’t any. As for what this function can return, there are no restrictions whatsoever. It can return any type (although it never will, because it can’t be called). In other words it’s a function that’s polymorphic in the return type. Haskellers have a name for it:

absurd :: Void -> a

The name is not coincidental. There is deeper interpretation of types and functions in terms of logic called the Curry-Howard isomorphism. The type Void represents falsity, and the type of the function absurd corresponds to the statement that from falsity follows anything, as in the Latin adage “ex falso sequitur quodlibet.”
** 1.3 Categories Great and Small
*** Empty category
The most trivial category is one with zero objects and, consequently, zero morphisms.
*** Simple graphs
You can build categories just by connecting objects with arrows. You can imagine starting with any directed graph and making it into a category by simply adding more arrows. First, add an identity arrow at each node. Then, for any two arrows such that the end of one coincides with the beginning of the other (in other words, any two composable arrows), add a new arrow to serve as their composition. Every time you add a new arrow, you have to also consider its composition with any other arrow (except for the identity arrows) and itself. You usually end up with infinitely many arrows, but that’s okay.
*** Orders
A category where a morphism is a relation between objects: the relation of being less than or equal. Let’s check if it indeed is a category. Do we have identity morphisms? Every object is less than or equal to itself: check! Do we have composition? If a <= b and b <= c then a <= c: check! Is composition associative? Check!
**** Preorder
An binary relation is a preorder if it is both reflexive and transitive.
***** Reflexive
A binary relation is reflexive if `x R x` (x is related to itself) for every x.
***** Transitive
A binary relation is transitive if `a R b` and `b R c` implies `a R c`.
**** Partial order
A partial order is a preorder that is also antisymmetric.
***** Antisymmetric
A binary relation is antisymmetric if `a R b` and `b R a` implies that `a = b`.
**** Total order (aka: linear order)
A partial order that is also total.
***** Total
A binary relation is total if for any two values `a` and `b`, `a R b` or `b R a`.
*** Monoid
A monoid is a single object category. In fact the name monoid comes from Greek mono, which means single. Every monoid can be described as a single object category with a set of morphisms that follow appropriate rules of composition.

All arrows compose, because all arrows in the Monoid category have the same beginning and end: the single object.
*** Hom-set
A set of morphisms from object a to object b in a category C is called a hom-set and is written as C(a, b) (or, sometimes, Hom_C(a, b)).

A lot of interesting phenomena in category theory have their root in the fact that elements of a hom-set can be seen both as morphisms, which follow the rules of composition, and as points in a set.
** 1.4 Kleisli Categories
A Kleisli category has, as objects, the types of the underlying programming language. Morphisms from type A to type B are functions that go from A to a type derived from B using the particular embellishment (e.g., logging). Each Kleisli category defines its own way of composing such morphisms, as well as the identity morphisms with respect to that composition.
* Video
YouTube series by Bartosz Milewski.
** Video 1.1: Motivation and Philosophy
*** Category Theory (CT) is one of the most abstract forms of math
*** Programming abstractions
**** Assembly
**** Procedures
**** Object Oriented Programming
*** Abstraction / Subtration -- Abstraction subtracts or hides details
*** The pains of OOP became apparent with concurrency and parallelism
*** OOP hides mutation and sharing, leads to race conditions
*** The OOP level abstraction doesn't handle concurrency and parallelism
*** From the high abstraction level of category of theory
**** all programming languages look the same
**** different fields of mathematics look the same, including logic
*** From a highly abstracted (subtracted) level, you can add in the required details to get a concreate implementation
*** is mathematics invented or discovered? category theory is what is discovered by mathematics
*** our brains have evolved to some things better than others
**** our brains are very good at visual processing, this has been evolving the longest
**** our higher level thinking abilities eveolved more recently, and were not super good at it
***** this is why we must abstract things, because our brains cannot hold all the complexity at once
***** without the strucutre provided by abstraction, we cannot "see"
***** in everything we do, we want to "chop things up", we want to abstract
*** it seems category might be the study of abstraction
*** stemology - how we reason or learn about stuff
*** ontology - what things are
** Video 1.2: What is a category?
*** The tools of our mind
**** abstraction - subtracting unnecessary details
**** composition
**** identity - after you abstract, things that are technically different become the same
*** Category Theory focuses on composition and identity
*** A category is a bunch of objects
*** A morphism (or arrow) is something that goes between two "objects"
*** What is an object? It has no properties.
*** What is an arrow? It goes from one object to another, and has no other properties.
*** Objects are just the two ends of arrows.
*** This is sounding very much like edges and vertexes in graphs.
**** These "graphs" can be infinite.
*** Composition
**** If f is an arrow from a to b, and g is an arrow from b to c, then g o f (g "of" f) must exist and goes from a to c.
*** Identify
**** For every object, there must be an identity arrow from a to a.
*** Arrows are associative: (f o g) o h = f o (g o h)
*** Example: Programming types and functions
**** types are objects
**** functions are arrows/morphisms
*** A category can be defined as a composition table
*** Forget the details
I expect one of the difficulties will be getting to an abstract enough level. For example, with the category Set, it will be difficult to forget the details and get to the level of abstraction of a category. Remember, to abstract you must subtract details.
*** Maximum abstraction
Category theory is as most abstract because you have abstracted away (subtracted) every detail about objects, except for relations (arrows) between them. You make no assumptions about the objects or the arrows. There is nothing left to subtract.
** Video 2.1: Functions, epimorphisms
*** Function purity test: can you memoize it?
*** The input set of a function is the domain, the possible outputs are the "image" and the image might be a subset of a "codomain"
*** a function that is invertable is called an "isomorphism"
*** 2 reasons a function is not invertable:
**** it maps 2 or more items in the domain to a single item in the codomain
**** the image of the function does not fill the codoamin
*** injective / surjective functions
**** an "injective" function does not "collapse"; it does not map any 2 values in the domain to the same value in the codomain
**** a "surjective" function has an image that covers the entire codomain
**** if a function is both injective and surjective, it is an isomorphism, meaning it is invertable
*** category theory terms
**** injective -> monic / monomorphism
**** surjective -> epic / epimorphism
*** epimorphism property in category theory
if forall g1 and g2, if g1 o f = g2 o f is proof that g1 = g2, then f is an epimorphism
*** it appear category theory will provide a framework for thinking about abstractions, once you recognize that something fits the paterns of a certain category theory concept, you will know the implications from category theory
** Video 2.2: Monomorphisms, simple types
*** monomorphism property in category theory
if forall g1 and g2, if f o g1 = f o g2 is proof that g1 = g2, then f is an monomorphism
*** notice the definitions of mono/epimorphisms only look at composition, and no other details
*** just because something is a monomorphism and an epimorphism doesn't mean it's an isomorphism in all categories
*** if we can use a microscope, use a telescope
**** to declare something a mono/epimorphism it's important to look at ALL possible g1,g2 pairs
*** Void, a type with no values, a set with no elements
**** there is a function `id_Void :: Void -> Void` but you can never call it
*** Unit, a type with one value, a set with one value
**** in Haskell `() :: ()` is the Unit
**** `f :: () -> Int` must be a constant integer
**** `f :: () -> Int` provides a trick to enumerate elements of a set at the category level
*** Bool
**** any two element type/set is equivalent to Bool
** Video 3.1: Examples of categories, orders, monoids
*** A category with no objects
**** Like zero, it's mainly useful in context with other numbers or categories
*** A category with 1 object
**** Has 1 arrow, the id arrow
***** every category must have an id arrow for every object
*** If you start with a graph that is not a category, it's ALWAYS possible to add arrows to make it a category
**** E.g. you might add id arrows
**** you must have compositions arrows
***** if an arrow goes from a to b, and another arrow goes from b to c, there must also be an arrow from a to c for it to be a category
****** this results in a lot of complete graphs I'd guess, does it aways result in a complete graph?
**** adding arrows to satisfy the axioms is called "free construction", and results in a "free category"
***** are all categories free?
*** order category
**** arrows mean "less than or equal"
**** a "pre-order" might not have an arrow between certain objects, but a "total-order" will be total
**** a "thin category" has a maximum of 1 arrow between any two objects
***** there can only be a maximum of 1 arrow from a to b, but there can be an arrow from b to a
**** a "partial order" is like a directed acyclic graph, there cannot be any "loops" between two objects or otherwise
*** a "home set" is a set of all arrows between two objects; it's written `c(a,b)`
*** it seems category theory is just graph theory combined with a lot of vocabulary to make it easy to talk about and reason about things
*** monoid - a category with 1 object
**** in monoid, all arrows are composable, because they begin and end at the same object
**** in monoid, the id arrow is called "unit"
**** a monoid must have "unit" (id) and the associative property when composing arrows
**** monoid examples: addition, multiplication, string concatenation
**** a monoid has only 1 home set
*** definition of unit: \exists e \forall a  e * a = a * e = a
** Video 3.2: Kleisli category
*** code simplicity
**** is simplicity measured in the number of lines of code?
**** simplicity is not easy
**** beware of hidden dependencies and long distance interactions
**** code smell: a function that "knows things" it shouldn't
*** functionality can be put into *composition* rather than into a regular function
**** remember: category theory is about identity and composition
**** when you hear or think abobut composition, you should think about category theory
*** in imperative programming, we don't think about composition
**** I think this is the divide between imperative and functional programming
**** a Monad provide an extra degree of freedom to composition
** Video 4.1: Terminal and initial objects
*** Kleisli category
**** example: a -> (b, string)
**** a -> (b, string) is a mirror of a -> b in another category
**** identity in Kleisli category is a mirror of a -> (a, string) in another category
**** composition works because you can break (b, string) up and then concatenate strings and recombine
**** the mirroring between the Kleisli category and the other category is called a monad
