#+STARTUP: latexpreview
* What are vectors?
There are a few different interpretations of what a vector is:

- a magnitude and a direction
- a tuple of numbers that form a type
- anything where there is a sensible definition of adding two vectors and multiplying by a scalar
** Types vs Vectors
An xy-coordinate and a tuple of ~(age, weight)~ are essentially the same. The operations that work on one will also work on the other.
** Tuple/point notation vs Vector notation
Where we might write a tuple or a vector as ~(1, 2)~ traditionally, we would write a vertical column matrix in linear algebra:

\begin{bmatrix}
1 \\
2
\end{bmatrix}
* Basic vector operations
** Vector addition
\begin{bmatrix}
1 \\
2
\end{bmatrix} +
\begin{bmatrix}
3 \\
4
\end{bmatrix} =
\begin{bmatrix}
1 + 3 \\
2 + 4
\end{bmatrix} =
\begin{bmatrix}
4 \\
6
\end{bmatrix}

A vector must contain values with units (types) that can be combined (added) in a sensible way.
** Vector scalar multiplication
\begin{align*}
3
\begin{bmatrix}
1 \\
2
\end{bmatrix} =
\begin{bmatrix}
3 \times 1 \\
3 \times 2
\end{bmatrix} =
\begin{bmatrix}
3 \\
6
\end{bmatrix}
\end{align*}
