#+STARTUP: entitiespretty
* Notation Drills
** Notation 1                                                        :drill:
What does this notation mean?

argmax_a f(a)
*** Answer
a value of a at which f(a) takes its maximal value
** Notation 2                                                        :drill:
What does this notation mean?

q_*(a)
*** Answer
true value of action a
** Notation 3                                                        :drill:
What does this notation mean?

Q_t(a)
*** Answer
estimate at time t of q_*(a)
** Notation 4                                                        :drill:
What does this notation mean?

A_t
*** Answer
action at time t
* Chapter 1 - The Reinforcement Learning Problem
** Notes
*** Elements of Reinforcement Learning
**** policy
"A policy defines the learning agent’s way of behaving at a given time. Roughly
speaking, a policy is a mapping from perceived states of the environment to actions to
be taken when in those states."
**** reward signal
"A reward signal defines the goal in a reinforcement learning problem. On each time
step, the environment sends to the reinforcement learning agent a single number, a
reward."
**** value function
"Whereas the reward signal indicates what is good in an immediate sense, a value
function specifies what is good in the long run. Roughly speaking, the value of
a state is the total amount of reward an agent can expect to accumulate over the
future, starting from that state."
** Drills
*** Elements of Reinforcement Learning                              :drill:
What are the 3 basic elements of reinforcement learning?
**** Answer
- policy
- reward signal
- value function
* Chapter 2 - Multi-arm Bandits
** TODO Skim chapter 2
Focus especially on the various exploration/exploitation methods.
